#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Airports.Models.MySql	
{
	public partial class Airlinereport
	{
		private int _reportId;
		public virtual int ReportId
		{
			get
			{
				return this._reportId;
			}
			set
			{
				this._reportId = value;
			}
		}
		
		private string _airlineName;
		public virtual string AirlineName
		{
			get
			{
				return this._airlineName;
			}
			set
			{
				this._airlineName = value;
			}
		}
		
		private int? _airlineId;
		public virtual int? AirlineId
		{
			get
			{
				return this._airlineId;
			}
			set
			{
				this._airlineId = value;
			}
		}
		
		private int? _totalFlightsCount;
		public virtual int? TotalFlightsCount
		{
			get
			{
				return this._totalFlightsCount;
			}
			set
			{
				this._totalFlightsCount = value;
			}
		}
		
		private float? _averageFlightsCount;
		public virtual float? AverageFlightsCount
		{
			get
			{
				return this._averageFlightsCount;
			}
			set
			{
				this._averageFlightsCount = value;
			}
		}
		
		private float? _totalFlightsDuration;
		public virtual float? TotalFlightsDuration
		{
			get
			{
				return this._totalFlightsDuration;
			}
			set
			{
				this._totalFlightsDuration = value;
			}
		}
		
		private DateTime? _startDate;
		public virtual DateTime? StartDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				this._startDate = value;
			}
		}
		
		private DateTime? _endDate;
		public virtual DateTime? EndDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				this._endDate = value;
			}
		}
		
	}
}
#pragma warning restore 1591
