//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airports.Data.SqlServer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class AirportsDbSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AirportsDbSettings defaultInstance = ((AirportsDbSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AirportsDbSettings())));
        
        public static AirportsDbSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Extended Properties=\"Excel 12.0" +
            " Xml;HDR=YES\";")]
        public string ExcelReaderConnectionString {
            get {
                return ((string)(this["ExcelReaderConnectionString"]));
            }
            set {
                this["ExcelReaderConnectionString"] = value;
            }
        }
    }
}
